[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileUtils = "3ab64cf3-766e-4aaa-abdf-a104b28521f5"
ITensorFormatter = "b6bf39f1-c9d3-4bad-aad8-593d802f65fd"

[sources.FileUtils]
path = ".."

[compat]
Documenter = "1"
FileUtils = "0.1"
ITensorFormatter = "0.2.27"
